spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        #The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: false #Set to true if you want to see the SQL statements made
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # validate, update, create, create-drop
    open-in-view: false
  sql:
    init:
      platform: postgres
      mode: always

server:
  port: 8080
